name: Build and Publish Packages

on:
  release:
    types: [published]

permissions:
  contents: read


jobs:
  build_and_publish_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Dependencies
      run: |
        pip install wheel twine
    - name: Add Rclone Binary File
      run: |
        cp linux/rclone rmount/rclone
    - name: Update Permissions
      run: |
        sudo chmod 755 rmount/rclone
    - name: Build And Package for Linux
      run: |
        make publish OS="manylinux1_x86_64"
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}